server:
  port: 8000


spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8010
              predicates:
                - Path=/auth/**
            - id: profile-service
              uri: http://localhost:8020
              predicates:
                  - Path=/profile/**
            - id: video-service
              uri: http://localhost:8030
              predicates:
                  - Path=/video/**
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              "[/**]":
                allowedOrigins:
                  - ${CORS_ALLOWED_ORIGIN}
                  - ${FRONTEND_LINK}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
  main:
    web-application-type: REACTIVE


jwt:
  secret: ${JWT_SECRET}
