server:
  port: 8000

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          codecs:
            max-in-memory-size: 100MB
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8010}
              predicates:
                - Path=/api/v1/auth/**
            - id: profile-service
              uri: ${PROFILE_SERVICE_URL:http://localhost:8020}
              predicates:
                - Path=/api/v1/profile/**
            - id: video-service
              uri: ${VIDEO_SERVICE_URL:http://localhost:8030}
              predicates:
                - Path=/api/v1/video/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL}
                  - http://localhost:5173
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
  http:
    codec:
      max-in-memory-size: 100MB
jwt:
  secret: ${JWT_SECRET_KEY}
