server:
  port: 8030

spring:
  application:
    name: video

  amqp:
    deserialization:
      trust:
        all: true

  dir:
    upload_dir: /uploads

  datasource:
    url: ${UPLOAD_DB_URL}
    username: ${UPLOAD_DB_USERNAME}
    password: ${UPLOAD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: video_exchange
  queue:
    video:
      process:
        name: video_processing_queue
        key: video.processing
      upload:
        name: video_upload_queue
        key: video.upload

cloudinary:
  name: ${CLOUDINARY_NAME}
  apikey: ${CLOUDINARY_API_KEY}
  apisecret: ${CLOUDINARY_API_SECRET}
